Removed doug lea allocator with ptmalloc
Im-dex/xray-162 pull request #57
Opened 2017-12-26 16:55 UTC by jazzvaz

Engine is working as expected, did not feel any difference in performance.

2017-12-26 19:41 UTC, Im-dex requested changes
Please, squash 0e55964af73e7e1dc0db68b5a338411ae213ce52 commit with 59be7f2ac8a77e77500c9093373ec91129e356c4, because it is redundant. Also, it would be nice to fix the commit message (confention -> convention)

2017-12-27 09:58 UTC, jazzvaz commented
Done, can you please check?

2017-12-27 11:24 UTC, Im-dex approved these changes

2017-12-27 11:25 UTC, merged

2017-12-27 11:25 UTC, Im-dex commented
@jazzvaz Thanks for your contribution