Memory rework, xr_new to new
Im-dex/xray-162 pull request #63
Opened 2018-01-16 08:23 UTC by jazzvaz

2018-01-16 15:15 UTC, jazzvaz commented
It is better to do something with utility because they just repeat engine files and each change should be also done there...

2018-01-16 15:18 UTC, jazzvaz commented on code/engine/xrCore/xrMemory.h
> +{
format fixed in next commit

2018-01-16 20:58 UTC, Im-dex commented
@jazzvaz 
>It is better to do something with utility because they repeat engine files and each change should be also made there...

Yep, they need some refactoring

2018-01-16 22:04 UTC, Im-dex commented
@jazzvaz Works well to me

2018-01-17 07:43 UTC, jazzvaz commented
@Im-dex I also have no problem

2018-01-17 12:58 UTC, Im-dex commented
@jazzvaz Nice, just fix formatting and I will merge it

2018-01-17 13:02 UTC, jazzvaz commented
@Im-dex which formatting? xr_memory format is fixed in the commit 

> replace xr_new with new

2018-01-17 13:05 UTC, Im-dex requested changes

2018-01-17 13:05 UTC, Im-dex commented on code/engine/xrCore/xrMemory.h
> +{
still broken

2018-01-17 13:05 UTC, Im-dex commented on code/engine/xrCore/xrMemory.h
> +//#pragma warning(push)
remove this

2018-01-17 14:58 UTC, jazzvaz commented
@Im-dex can you test again, as I changed xrCDB memory calls.

2018-01-18 21:15 UTC, Im-dex commented
@jazzvaz seems works nice, thanks.

2018-01-18 21:16 UTC, merged