Memory and xr_containers refactor
Im-dex/xray-162 pull request #64
Opened 2018-01-20 09:33 UTC by jazzvaz

2018-01-20 15:42 UTC, Im-dex requested changes

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrCore/LzHuf.cpp
> +        out_start = new u8[_rsize / sizeof(u8)];
redundant division

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrCore/LzHuf.cpp
> +    u8* data = new u8[size / sizeof(u8)];
redundant division

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrCore/os_clipboard.cpp
> +    LPSTR buffer = new char[buffer_size];
It will be better to  keep _alloca

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrEngine/ai_script_lua_extension.cpp
> -#ifdef DEBUG
What for?

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrEngine/tntQAVI.cpp
> +    m_pMovieData = new BYTE[mmckinfoSubchunk.cksize / sizeof(BYTE)];
redundant division

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrEngine/xrImage_Resampler.cpp
> +    if ((0 != (image = new Image)) &&
new never returns null

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrServerEntities/script_storage.cpp
>          } __except (GetExceptionCode() == STATUS_STACK_OVERFLOW) {
remove stackoverflow catch and reset, cause there is no alloca anymore

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrEngine/tntQAVI.cpp
> +    m_pDecompressedBuf = new BYTE[m_dwWidth * m_dwHeight + 1];
wrong size

2018-01-20 15:42 UTC, Im-dex commented on code/engine/xrCore/_stl_extensions.h
> +template <typename T>
Don't remove allocator

2018-01-20 15:42 UTC, Im-dex commented on code/utils/xrDO_Light/StdAfx.h
> +IC std::string string2std::string(LPCSTR s) { return s ? s : ""; }
invalid

2018-01-21 15:08 UTC, Im-dex requested changes

2018-01-21 15:08 UTC, Im-dex commented on code/utils/xrDO_Light/StdAfx.h
>  #define THROW2(xpr, msg0)                                                                          \
c_str usage is redundant

2018-01-21 15:08 UTC, Im-dex commented on code/utils/xrDO_Light/StdAfx.h
>  #define THROW3(xpr, msg0, msg1)              \
c_str usage is redundant

2018-01-21 15:08 UTC, Im-dex commented on code/utils/xrAI/StdAfx.h
> -        throw * shared_str(xr_string(__FILE__LINE__)           \
c_str usage is redundant

2018-01-21 15:08 UTC, Im-dex commented on code/utils/xrAI/StdAfx.h
>  #define THROW3(xpr, msg0, msg1)                                \
c_str usage is redundant

2018-01-22 11:04 UTC, jazzvaz commented on code/utils/xrDO_Light/StdAfx.h
>  #define THROW2(xpr, msg0)                                                                          \
fixed

2018-01-24 13:28 UTC, Im-dex approved these changes
Thanks

2018-01-24 13:28 UTC, merged